# fly.toml app configuration file generated for sesc-bot on 2025-08-27T08:05:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sesc-bot'
primary_region = 'gig'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  HEARTBEAT_PATH = '/app/data/heartbeat.json'
  LIVENESS_WINDOW_SEC = '1800'

# Persistent volume for DB and heartbeat
[[mounts]]
  source = 'sesc_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
